apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-app
  namespace: mantogin-hw7
  labels:
    app: order-app
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: order-app
  template:
    metadata:
      labels:
        app: order-app
    spec:
      containers:
        - name: order-app
          image: mantogin/order-app:1.0.0
          ports:
            - containerPort: 8001
